# Generated by Django 4.2.3 on 2023-08-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Message.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Soluton',
        ),
    ]
