# Generated by Django 5.0.6 on 2024-06-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0005_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(max_length=1000, null=True)),
                ('url_to_image', models.URLField(max_length=1000, null=True)),
            ],
        ),
    ]
