# Generated by Django 4.2.3 on 2023-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='titile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
