# Generated by Django 4.2.3 on 2023-07-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_category_category_name_alter_occupation_titile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='static/img/userprofile.jpg', null=True, upload_to='cover/'),
        ),
    ]
