# Generated by Django 4.2.3 on 2023-07-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_user_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.category'),
        ),
    ]
