# Generated by Django 4.2.3 on 2023-07-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_user_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
    ]
