# Generated by Django 4.2.3 on 2023-07-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_address_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Occupation'},
        ),
    ]
