# Generated by Django 4.2.3 on 2023-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
