# Generated by Django 4.2.3 on 2023-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
