# Generated by Django 4.2.3 on 2023-07-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='Banner'),
        ),
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='Member'),
        ),
    ]
