# Generated by Django 4.2.3 on 2023-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_banner_img_alter_member_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_list',
            field=models.BooleanField(default=False),
        ),
    ]
