# Generated by Django 4.2.3 on 2023-08-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_user_is_setup_complete'),
        ('Home', '0005_alter_banner_title_alter_member_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.category'),
        ),
    ]
